[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "gunicorn project.wsgi:application --bind 0.0.0.0:$PORT"
healthcheckPath = "/admin/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[phases.setup]
nixPkgs = ["python39", "gcc"]
