[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/admin/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[phases.setup]
nixPkgs = ["python39", "gcc"]

[phases.install]
cmds = ["python -m venv --copies /opt/venv", ". /opt/venv/bin/activate", "pip install -r requirements.txt"]

[phases.build]
cmds = ["python manage.py collectstatic --noinput"]

[start]
cmd = "gunicorn project.wsgi:application --bind 0.0.0.0:$PORT"
