# Generated by Django 5.1.7 on 2025-03-30 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0002_alter_user_options_translation_is_favorite_and_more'),
    ]

    operations = [
    ]
